# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: INFO
        com.revolut: DEBUG

spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
            additional-exclude: .h2.server.properties
        livereload:
            enabled: true
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:revolut;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: revolut
        password:
    h2:
        console:
            enabled: false
    jpa:
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.generate_statistics: true

server:
    port: 8081


# application:
