apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-revolut
  namespace: default
spec:
  replicas: {{ .Values.helloworld.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-revolut
      version: "v1"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-revolut
        version: "v1"
    spec:
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
                while true
                do
                  rt=$(nc -z -w 1 revolut-mysql 3306)
                  if [ $? -eq 0 ]; then
                    echo "DB is UP"
                    break
                  fi
                  echo "DB is not yet reachable;sleep for 10s before retry"
                  sleep 10
                done
      containers:
      - name: revolut-helloworld
        image: pkrishnath/revolut-helloworld
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://revolut-mysql:3306/{{ .Values.mysql.mysqlDatabase }}?useUnicode=true&characterEncoding=utf8&useSSL=false
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.mysql.mysqlUser }}
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.mysql.mysqlPassword }}
          - name: JAVA_OPTS
            value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 120
