apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-revolut
  namespace: default
  labels:
    app: {{ template "fullname" . }}-revolut
spec:
  selector:
    app: {{ template "fullname" . }}-revolut
  ports:
  - name: http
    port: 8081
